# 機械学習帳 確認問題(12.7)

[機械学習帳の主成分分析の確認問題(12.7)](https://chokkan.github.io/mlnote/unsupervised/03pca.html#id8)を解きます。

## 講義内容の復習

![chapter12-1.svg](./images/chapter12/chapter12-1.svg)

![chapter12-2.svg](./images/chapter12/chapter12-2.svg)

## 1. $\pmb{S}$の計算

行列$\pmb{S} = \pmb{X}^\top \pmb{X}$に対して固有値問題を解くことで、主成分分析が得られることを確認したい。

$\pmb{X}$に対して、行列$\pmb{S} = \pmb{X}^\top \pmb{X}$を求めよ。

\begin{align*}
\pmb{X} = \begin{pmatrix}-7 & -2 \\ -3 & -3 \\ 4 & 1 \\ 6 & 4\end{pmatrix}
\end{align*}

In [1]:
import numpy as np


X = np.array([[-7, -2,],
              [-3, -3,],
              [4, 1],
              [6, 4]])

In [2]:
S = X.T @ X
S

array([[110,  51],
       [ 51,  30]])

## 2. 固有値問題の解

[numpy.linalg.eig](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html)等で$\pmb{S}$の固有値問題を解き、固有値と固有ベクトルを求めよ。

In [3]:
eigvals, eigenvectors = np.linalg.eig(S)

In [4]:
eigvals

array([134.81512169,   5.18487831])

In [5]:
eigenvectors

array([[ 0.89920519, -0.43752718],
       [ 0.43752718,  0.89920519]])

scikit-learnの主成分分析と実質結果が等しくなることを確認する。

In [6]:
from sklearn.decomposition import PCA


pca = PCA(n_components=2)
pca.fit(X)

PCA(n_components=2)

In [7]:
pca.components_

array([[-0.89920519, -0.43752718],
       [ 0.43752718, -0.89920519]])

In [8]:
pca.singular_values_ ** 2

array([134.81512169,   5.18487831])

## 3. 第１主成分と第２主成分

第１主成分と第１主成分軸における分散、第２主成分と第２主成分軸における分散を求めよ。

(12.29)より、固有値が目的関数(分散)の値と等しくなることからそれぞれの分散は次の通りとなる。

In [9]:
eigvals

array([134.81512169,   5.18487831])

## 第１主成分得点と第２主成分得点

第１主成分得点と第２主成分得点を求めよ。

第一主成分得点は次の通り。

In [10]:
X @ eigenvectors[:,0]

array([-7.16949066, -4.0101971 ,  4.03434793,  7.14533984])

In [11]:
X @ eigenvectors[:,1]

array([ 1.26427988, -1.38503402, -0.85090353,  0.97165767])

scikit-learnの結果と実質一致することを確認する。

In [12]:
pca.transform(X)

array([[ 7.16949066, -1.26427988],
       [ 4.0101971 ,  1.38503402],
       [-4.03434793,  0.85090353],
       [-7.14533984, -0.97165767]])